---
name: Test-Perl-Critic
version: 1.02
author:
  - 'Jeffrey Thalhammer <thaljef@cpan.org>'
abstract: Use Perl::Critic in test programs.
license: perl
resources:
  MailingList: http://perlcritic.tigris.org/servlets/SummarizeList?listName=users
  Repository: http://guest@perlcritic.tigris.org/svn/perlcritic/trunk/distributions/Test-Perl-Critic/
  homepage: http://perlcritic.com
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
requires:
  Carp: 0
  English: 0
  Perl::Critic: 1.105
  Perl::Critic::Utils: 1.105
  Perl::Critic::Violation: 1.105
  Test::Builder: 0
  strict: 0
  warnings: 0
configure_requires:
  Module::Build: 0.35
dynamic_config: 1
provides:
  Test::Perl::Critic:
    file: lib/Test/Perl/Critic.pm
    version: 1.02
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
